<?xml version="1.0"?>
<package format="3">
<name>x_bot_common</name><version>0.2.0</version><description>x bot common</description>
<maintainer email="maintainer@example.com">Embodied RobotSim maintainers</maintainer><license>Apache-2.0</license>
<buildtool_depend>ament_cmake</buildtool_depend>
<buildtool_depend>ament_cmake_python</buildtool_depend>
<depend>geometry_msgs</depend>
<depend>python3-numpy</depend>
<test_depend>ament_cmake_gtest</test_depend>
<export><build_type>ament_cmake</build_type></export>
</package>
